### ISSUE TITLE
Ubuntu VPS server.

### ISSUE THREAD

**Issue by ingnelson** [git-davi/reverse-proxy-port-forwarder#1]
Hello sir.
Can you give the command to install and run the server on a UBUNTU VPS , please .?
I am a little confused about the binary.
I do not know how to Install it and run it .
Please I bet your help , it won't take you to much time . Please .
I really want to use it.

I will wait your answer.

**Comment by git-davi** [comment]
Hi :)
To create a tunnel you need only two files, remote and local. Those can be the binaries or just scripts .
I highly recommend to use the python scripts which are much easier.
Binaries are only for some use cases and sometimes they couldn't work.
Just upload remote.py to your VPS and then run local.py in your local machine.

There is no installation.
Just upload and run :)

On bottom of README.md you can find an example.
Still here if you need help.

Regards

**Comment by git-davi** [comment]
Also you made me notice that the "reverse-proxy-port-forwarder" name can be misleading on the real purpose.
So I will consider to rename the project.
